### ISSUE TITLE
Error when running flick_data_to_matrix.py

### ISSUE THREAD

**Issue by Quasimondo** [rynmurdock/generative_recommender#1]
When running flick_data_to_matrix.py on the csv downloaded from iccv_17_aesthetics_dataset I get an error, which seems to be caused by some spaces in the column names:
AttributeError: 'DataFrame' object has no attribute 'imagePair'

I was able to fix this by adding this line after the loading of the csv:

```
ratings = pd.read_csv('data/FLICKR-AES_image_labeled_by_each_worker.csv', delimiter=',',)

ratings.columns = ratings.columns.str.strip()
```

**Comment by rynmurdock** [comment]
Thanks for this!
I'll see if there are any other versions of the csv that they've shared (in case they have slightly different formats) & then add the change :)

**Comment by rynmurdock** [comment]
7cf24ba7c7eb4d439f952749e8a349f37428a185 Thanks, Mario!
