### ISSUE TITLE
What is the for_model string for non-Kandinsky models in flick_embed_images_each_to_each.py?

### ISSUE THREAD

**Issue by Quasimondo** [rynmurdock/generative_recommender#2]
I wonder what I have to enter if I want to calculate the embeddings for SDXL + IP Adapter?

**Comment by rynmurdock** [comment]
The default `'kandinsky'` version will work so long as you use the IP Adapter version supplied in the https://github.com/rynmurdock/generative_recommender/blob/main/gradio_app/ip_serve_sdxl.py file -- they use the same CLIP model.

Apologies for any similarly vague variable names & lack of docs here -- wasn't sure I'd be able to release until recently :smile:
