### ISSUE TITLE
Small inconsistency: each_to_each_filtered.hdf vs. flick_each_to_each_filtered.hdf

### ISSUE THREAD

**Issue by Quasimondo** [rynmurdock/generative_recommender#3]
This is just a minor issue and easily fixed:
The flick_embed_images_each_to_each.py script saves the data in a file named "each_to_each_filtered.hdf" but flick_score_images.py tries to load a file named "flick_each_to_each_filtered.hdf"

**Comment by rynmurdock** [comment]
ah thank you, will put this on my list of revisions!

**Comment by rynmurdock** [comment]
Should be fixed by 7cf24ba7c7eb4d439f952749e8a349f37428a185
